name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: release-candidate
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Run tests
      run: gradle clean test

    - name: Check that ParameterizedTest report is present
      run: test -f ./build/test-results/test/TEST-org.example.ParameterizedTest.xml

    - name: Dry run tests
      run: gradle clean test --test-dry-run

    - name: Check that dry-run ParameterizedTest report is present
      run: test -f ./build/test-results/test/TEST-org.example.ParameterizedTest.xml
